---
title: "LeBron's Teammates Clustering Analysis"
author: "Zachary Jesse"
---

## The K-means Analysis

::: {layout="[ [1], [1] ]"}

```{r}
#| echo: FALSE 
#| fig.width: 10
#| fig.height: 10
#| warning: FALSE

ggplot(Stats_stdz_c3, aes(x = PTS_z, y = AST_z, color = cluster)) +
  geom_point(size = 3) +
  facet_wrap(~ Team) +
  labs(title = "Clustering of LeBron’s Teammates Based on Teams He Played For",
       x = "Standardized Points per Game (PTS_z)",
       y = "Standardized Assists per Game (AST_z)",
       color = "Cluster") +
  theme_minimal()
```

The clustering visualized above is separated by the different teams players played with LeBron. 

- Cluster 1 are average players. These players were important to the team and put up average and slightly above average points and assists
- Cluster 2 are below average players/bench players. These players did not have a big impact on the team and put up below average points and Assists
- Cluster 3 are superstars that played with LeBron. These players put up high point and assist averages while playing with LeBron

We are able to see that there was only one considered superstar that played with LeBron on the Miami Heat. This is when LeBron was playing his best basketball as he was not surrounded by the talent he was surrounded with on the Cavaliers and Lakers. [More to be Added]